package dk.molslinjen.ui.views.global.navigation;

import com.ramcosta.composedestinations.generated.destinations.AccountActivationScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.AddExistingTicketScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.AddonsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.AgreementsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.BarcodeDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.BookingSummaryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.BornholmCommuterAddScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.BornholmCommuterDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CalendarScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CargoDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ChangePasswordScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CheckoutDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CheckoutPassengerCreateScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CheckoutPassengerEditScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CommuterTicketHistoryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ContactScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.CurrenciesScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeepLinkScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeparturesCommuterScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeparturesEditScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeparturesMultiRideScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeparturesReturnScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeparturesScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeveloperBottomSheetWithStickyScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeveloperComponentsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeveloperInputComponentsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.DeveloperNavigationScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInAddonsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInFoodScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInPassengerCreateScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInPassengerEditScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInPassengerSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInProcessingScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.EarlyCheckInScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.FaqScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.FaqSubjectScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.FerryFloorSectionsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.FerrySectionSeatsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.FoodBarcodeDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.FoodScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ForgotPasswordScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.LoginScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.LoungeBarcodeDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRideAddCardScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRideCardPurchaseSummaryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRideDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRidePurchaseReceiptScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRidePurchaseScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRideRefillScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.MultiRideTicketHistoryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.NationalitySelectionScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.OeresundCommuterDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.OnboardingLocationScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.OnboardingLoginScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.OnboardingMarketingNotificationsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.OnboardingNotificationsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.OnboardingSelectRouteScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PassengerCountScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PassengerCountSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PassengerHelpScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PassengersScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PaymentBottomSheetScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PaymentScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PermissionsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.PhoneNumberCodeSelectionScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileBrobizzRegisterScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileBrobizzScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileCreditCardsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileEditScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileNewslettersScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfilePassengerEditScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfilePassengersRegisterScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfilePassengersScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileVehicleEditScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileVehiclesRegisterScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ProfileVehiclesScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ReceiptScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.RefundReceiptScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.ResetPasswordScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.RouteSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardBarcodeDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardBasketScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardDepartureSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardFoodListScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardOrderDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardOrderHistoryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardProductDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardReceiptScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SaleOnBoardScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SignupScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SimpleChangeAddonsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SimpleChangeFoodScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SimpleChangeReceiptScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.SimpleChangeSummaryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TicketDetailsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TicketHistoryScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TicketTypeScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TicketsScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TrailerSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TransportProductSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.TransportationSelectorScreenDestination;
import com.ramcosta.composedestinations.generated.destinations.VehicleSelectorScreenDestination;
import dk.molslinjen.kombardo.R;
import dk.molslinjen.ui.views.global.navigation.SimpleScreenConfig;
import dk.molslinjen.ui.views.global.topbar.NavigationButton;
import dk.molslinjen.ui.views.global.topbar.TopBarButtonType;
import dk.molslinjen.ui.views.global.topbar.TopBarConfiguration;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.conscrypt.BuildConfig;

@Metadata(d1 = {"\u0000\u000e\n\u0000\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0017\u0010\u0000\u001a\b\u0012\u0004\u0012\u00020\u00020\u0001¢\u0006\b\n\u0000\u001a\u0004\b\u0003\u0010\u0004¨\u0006\u0005"}, d2 = {"screenConfigurations", BuildConfig.FLAVOR, "Ldk/molslinjen/ui/views/global/navigation/SimpleScreenConfig;", "getScreenConfigurations", "()Ljava/util/List;", "app_kombardoProd"}, k = 2, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes2.dex */
public abstract class ScreenConfigurationsKt {
    private static final List<SimpleScreenConfig> screenConfigurations;

    static {
        DeepLinkScreenDestination deepLinkScreenDestination = DeepLinkScreenDestination.INSTANCE;
        ComposableSingletons$ScreenConfigurationsKt composableSingletons$ScreenConfigurationsKt = ComposableSingletons$ScreenConfigurationsKt.INSTANCE;
        SimpleScreenConfig createScreenConfig$default = SimpleScreenConfigKt.createScreenConfig$default(deepLinkScreenDestination, null, null, composableSingletons$ScreenConfigurationsKt.m3282getLambda1$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default2 = SimpleScreenConfigKt.createScreenConfig$default(OnboardingSelectRouteScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3293getLambda2$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default3 = SimpleScreenConfigKt.createScreenConfig$default(OnboardingNotificationsScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3304getLambda3$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default4 = SimpleScreenConfigKt.createScreenConfig$default(OnboardingMarketingNotificationsScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3315getLambda4$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default5 = SimpleScreenConfigKt.createScreenConfig$default(OnboardingLocationScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3326getLambda5$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default6 = SimpleScreenConfigKt.createScreenConfig$default(OnboardingLoginScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3337getLambda6$app_kombardoProd(), 2, null);
        SaleOnBoardScreenDestination saleOnBoardScreenDestination = SaleOnBoardScreenDestination.INSTANCE;
        SimpleScreenConfig.Companion companion = SimpleScreenConfig.INSTANCE;
        SimpleScreenConfig createScreenConfig = SimpleScreenConfigKt.createScreenConfig(saleOnBoardScreenDestination, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.saleOnBoard_title), null, CollectionsKt.listOf(TopBarButtonType.Profile), 5, null), companion.getDefaultBottomNavConfig(), composableSingletons$ScreenConfigurationsKt.m3348getLambda7$app_kombardoProd());
        SaleOnBoardFoodListScreenDestination saleOnBoardFoodListScreenDestination = SaleOnBoardFoodListScreenDestination.INSTANCE;
        TopBarConfiguration defaultTopBarConfig = companion.getDefaultTopBarConfig();
        NavigationButton.Back back = NavigationButton.Back.INSTANCE;
        SimpleScreenConfig createScreenConfig$default7 = SimpleScreenConfigKt.createScreenConfig$default(saleOnBoardFoodListScreenDestination, TopBarConfiguration.copy$default(defaultTopBarConfig, false, Integer.valueOf(R.string.saleOnBoard_foodList_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3359getLambda8$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default8 = SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardDepartureSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3370getLambda9$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default9 = SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardProductDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3283getLambda10$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default10 = SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardBasketScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.saleOnBoard_basket_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3284getLambda11$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default11 = SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardReceiptScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3285getLambda12$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default12 = SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardOrderDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3286getLambda13$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default13 = SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardOrderHistoryScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.saleOnBoard_orderHistory_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3287getLambda14$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default14 = SimpleScreenConfigKt.createScreenConfig$default(LoginScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3288getLambda15$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default15 = SimpleScreenConfigKt.createScreenConfig$default(ForgotPasswordScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3289getLambda16$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default16 = SimpleScreenConfigKt.createScreenConfig$default(ResetPasswordScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3290getLambda17$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default17 = SimpleScreenConfigKt.createScreenConfig$default(AccountActivationScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3291getLambda18$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default18 = SimpleScreenConfigKt.createScreenConfig$default(SignupScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3292getLambda19$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default19 = SimpleScreenConfigKt.createScreenConfig$default(NationalitySelectionScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3294getLambda20$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default20 = SimpleScreenConfigKt.createScreenConfig$default(PhoneNumberCodeSelectionScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3295getLambda21$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default21 = SimpleScreenConfigKt.createScreenConfig$default(ProfileScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3296getLambda22$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default22 = SimpleScreenConfigKt.createScreenConfig$default(ProfileEditScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3297getLambda23$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default23 = SimpleScreenConfigKt.createScreenConfig$default(ChangePasswordScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3298getLambda24$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default24 = SimpleScreenConfigKt.createScreenConfig$default(ProfileVehiclesScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3299getLambda25$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default25 = SimpleScreenConfigKt.createScreenConfig$default(ProfileVehiclesRegisterScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3300getLambda26$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default26 = SimpleScreenConfigKt.createScreenConfig$default(ProfileVehicleEditScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3301getLambda27$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default27 = SimpleScreenConfigKt.createScreenConfig$default(ProfileNewslettersScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3302getLambda28$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default28 = SimpleScreenConfigKt.createScreenConfig$default(ProfileCreditCardsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3303getLambda29$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default29 = SimpleScreenConfigKt.createScreenConfig$default(ProfilePassengersScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3305getLambda30$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default30 = SimpleScreenConfigKt.createScreenConfig$default(ProfilePassengersRegisterScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3306getLambda31$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default31 = SimpleScreenConfigKt.createScreenConfig$default(ProfilePassengerEditScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3307getLambda32$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default32 = SimpleScreenConfigKt.createScreenConfig$default(CurrenciesScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3308getLambda33$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default33 = SimpleScreenConfigKt.createScreenConfig$default(ProfileBrobizzScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3309getLambda34$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default34 = SimpleScreenConfigKt.createScreenConfig$default(ProfileBrobizzRegisterScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3310getLambda35$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default35 = SimpleScreenConfigKt.createScreenConfig$default(ContactScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3311getLambda36$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default36 = SimpleScreenConfigKt.createScreenConfig$default(FaqScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3312getLambda37$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default37 = SimpleScreenConfigKt.createScreenConfig$default(FaqSubjectScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3313getLambda38$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default38 = SimpleScreenConfigKt.createScreenConfig$default(PermissionsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3314getLambda39$app_kombardoProd(), 3, null);
        DeparturesScreenDestination departuresScreenDestination = DeparturesScreenDestination.INSTANCE;
        TopBarConfiguration defaultTopBarConfig2 = companion.getDefaultTopBarConfig();
        Integer valueOf = Integer.valueOf(R.string.departuresScreen_title);
        SimpleScreenConfig createScreenConfig2 = SimpleScreenConfigKt.createScreenConfig(departuresScreenDestination, TopBarConfiguration.copy$default(defaultTopBarConfig2, false, valueOf, null, null, 13, null), companion.getDefaultBottomNavConfig(), composableSingletons$ScreenConfigurationsKt.m3316getLambda40$app_kombardoProd());
        SimpleScreenConfig createScreenConfig$default39 = SimpleScreenConfigKt.createScreenConfig$default(DeparturesReturnScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, valueOf, null, null, 13, null), null, composableSingletons$ScreenConfigurationsKt.m3317getLambda41$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default40 = SimpleScreenConfigKt.createScreenConfig$default(DeparturesEditScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, valueOf, null, null, 13, null), null, composableSingletons$ScreenConfigurationsKt.m3318getLambda42$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default41 = SimpleScreenConfigKt.createScreenConfig$default(DeparturesMultiRideScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, valueOf, null, null, 13, null), null, composableSingletons$ScreenConfigurationsKt.m3319getLambda43$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default42 = SimpleScreenConfigKt.createScreenConfig$default(DeparturesCommuterScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, valueOf, null, null, 13, null), null, composableSingletons$ScreenConfigurationsKt.m3320getLambda44$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default43 = SimpleScreenConfigKt.createScreenConfig$default(CalendarScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3321getLambda45$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig3 = SimpleScreenConfigKt.createScreenConfig(TicketsScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.ticketsScreen_title), null, null, 13, null), companion.getDefaultBottomNavConfig(), composableSingletons$ScreenConfigurationsKt.m3322getLambda46$app_kombardoProd());
        TicketHistoryScreenDestination ticketHistoryScreenDestination = TicketHistoryScreenDestination.INSTANCE;
        TopBarConfiguration defaultTopBarConfig3 = companion.getDefaultTopBarConfig();
        Integer valueOf2 = Integer.valueOf(R.string.ticketsHistory_title);
        SimpleScreenConfig createScreenConfig$default44 = SimpleScreenConfigKt.createScreenConfig$default(ticketHistoryScreenDestination, TopBarConfiguration.copy$default(defaultTopBarConfig3, false, valueOf2, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3323getLambda47$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default45 = SimpleScreenConfigKt.createScreenConfig$default(TicketDetailsScreenDestination.INSTANCE, new TopBarConfiguration(false, Integer.valueOf(R.string.ticketDetails_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3324getLambda48$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default46 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3325getLambda49$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig4 = SimpleScreenConfigKt.createScreenConfig(AgreementsScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.agreementsScreen_title), null, null, 13, null), companion.getDefaultBottomNavConfig(), composableSingletons$ScreenConfigurationsKt.m3327getLambda50$app_kombardoProd());
        SimpleScreenConfig createScreenConfig$default47 = SimpleScreenConfigKt.createScreenConfig$default(MultiRideDetailsScreenDestination.INSTANCE, new TopBarConfiguration(false, Integer.valueOf(R.string.multiRide), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3328getLambda51$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default48 = SimpleScreenConfigKt.createScreenConfig$default(MultiRideTicketHistoryScreenDestination.INSTANCE, new TopBarConfiguration(false, valueOf2, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3329getLambda52$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default49 = SimpleScreenConfigKt.createScreenConfig$default(MultiRideRefillScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3330getLambda53$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default50 = SimpleScreenConfigKt.createScreenConfig$default(MultiRidePurchaseScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3331getLambda54$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default51 = SimpleScreenConfigKt.createScreenConfig$default(MultiRideCardPurchaseSummaryScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3332getLambda55$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default52 = SimpleScreenConfigKt.createScreenConfig$default(MultiRidePurchaseReceiptScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3333getLambda56$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default53 = SimpleScreenConfigKt.createScreenConfig$default(MultiRideAddCardScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3334getLambda57$app_kombardoProd(), 3, null);
        BornholmCommuterDetailsScreenDestination bornholmCommuterDetailsScreenDestination = BornholmCommuterDetailsScreenDestination.INSTANCE;
        Integer valueOf3 = Integer.valueOf(R.string.commuter);
        SimpleScreenConfig createScreenConfig$default54 = SimpleScreenConfigKt.createScreenConfig$default(bornholmCommuterDetailsScreenDestination, new TopBarConfiguration(false, valueOf3, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3335getLambda58$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default55 = SimpleScreenConfigKt.createScreenConfig$default(OeresundCommuterDetailsScreenDestination.INSTANCE, new TopBarConfiguration(false, valueOf3, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3336getLambda59$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default56 = SimpleScreenConfigKt.createScreenConfig$default(CommuterTicketHistoryScreenDestination.INSTANCE, new TopBarConfiguration(false, valueOf2, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3338getLambda60$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default57 = SimpleScreenConfigKt.createScreenConfig$default(BornholmCommuterAddScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3339getLambda61$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default58 = SimpleScreenConfigKt.createScreenConfig$default(RouteSelectorScreenDestination.INSTANCE, null, null, null, 7, null);
        SimpleScreenConfig createScreenConfig$default59 = SimpleScreenConfigKt.createScreenConfig$default(TransportationSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3340getLambda62$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default60 = SimpleScreenConfigKt.createScreenConfig$default(CargoDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3341getLambda63$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default61 = SimpleScreenConfigKt.createScreenConfig$default(PassengerCountSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3342getLambda64$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default62 = SimpleScreenConfigKt.createScreenConfig$default(TrailerSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3343getLambda65$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default63 = SimpleScreenConfigKt.createScreenConfig$default(TransportProductSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3344getLambda66$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default64 = SimpleScreenConfigKt.createScreenConfig$default(TicketTypeScreenDestination.INSTANCE, null, null, null, 7, null);
        SimpleScreenConfig createScreenConfig$default65 = SimpleScreenConfigKt.createScreenConfig$default(SimpleChangeAddonsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3345getLambda67$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default66 = SimpleScreenConfigKt.createScreenConfig$default(SimpleChangeFoodScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3346getLambda68$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default67 = SimpleScreenConfigKt.createScreenConfig$default(SimpleChangeSummaryScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3347getLambda69$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default68 = SimpleScreenConfigKt.createScreenConfig$default(SimpleChangeReceiptScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3349getLambda70$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default69 = SimpleScreenConfigKt.createScreenConfig$default(PaymentBottomSheetScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3350getLambda71$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default70 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInProcessingScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3351getLambda72$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default71 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInPassengerCreateScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3352getLambda73$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default72 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInPassengerEditScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3353getLambda74$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default73 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInAddonsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3354getLambda75$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default74 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInFoodScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3355getLambda76$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default75 = SimpleScreenConfigKt.createScreenConfig$default(EarlyCheckInPassengerSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3356getLambda77$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default76 = SimpleScreenConfigKt.createScreenConfig$default(BookingSummaryScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.bookingSummary_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3357getLambda78$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default77 = SimpleScreenConfigKt.createScreenConfig$default(AddonsScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.addons_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3358getLambda79$app_kombardoProd(), 2, null);
        SimpleScreenConfig createScreenConfig$default78 = SimpleScreenConfigKt.createScreenConfig$default(FerryFloorSectionsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3360getLambda80$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default79 = SimpleScreenConfigKt.createScreenConfig$default(FerrySectionSeatsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3361getLambda81$app_kombardoProd(), 3, null);
        SimpleScreenConfig createScreenConfig$default80 = SimpleScreenConfigKt.createScreenConfig$default(FoodScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.food_title), back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3362getLambda82$app_kombardoProd(), 2, null);
        PassengersScreenDestination passengersScreenDestination = PassengersScreenDestination.INSTANCE;
        TopBarConfiguration defaultTopBarConfig4 = companion.getDefaultTopBarConfig();
        Integer valueOf4 = Integer.valueOf(R.string.passengers_title);
        screenConfigurations = CollectionsKt.listOf((Object[]) new SimpleScreenConfig[]{createScreenConfig$default, createScreenConfig$default2, createScreenConfig$default3, createScreenConfig$default4, createScreenConfig$default5, createScreenConfig$default6, createScreenConfig, createScreenConfig$default7, createScreenConfig$default8, createScreenConfig$default9, createScreenConfig$default10, createScreenConfig$default11, createScreenConfig$default12, createScreenConfig$default13, createScreenConfig$default14, createScreenConfig$default15, createScreenConfig$default16, createScreenConfig$default17, createScreenConfig$default18, createScreenConfig$default19, createScreenConfig$default20, createScreenConfig$default21, createScreenConfig$default22, createScreenConfig$default23, createScreenConfig$default24, createScreenConfig$default25, createScreenConfig$default26, createScreenConfig$default27, createScreenConfig$default28, createScreenConfig$default29, createScreenConfig$default30, createScreenConfig$default31, createScreenConfig$default32, createScreenConfig$default33, createScreenConfig$default34, createScreenConfig$default35, createScreenConfig$default36, createScreenConfig$default37, createScreenConfig$default38, createScreenConfig2, createScreenConfig$default39, createScreenConfig$default40, createScreenConfig$default41, createScreenConfig$default42, createScreenConfig$default43, createScreenConfig3, createScreenConfig$default44, createScreenConfig$default45, createScreenConfig$default46, createScreenConfig4, createScreenConfig$default47, createScreenConfig$default48, createScreenConfig$default49, createScreenConfig$default50, createScreenConfig$default51, createScreenConfig$default52, createScreenConfig$default53, createScreenConfig$default54, createScreenConfig$default55, createScreenConfig$default56, createScreenConfig$default57, createScreenConfig$default58, createScreenConfig$default59, createScreenConfig$default60, createScreenConfig$default61, createScreenConfig$default62, createScreenConfig$default63, createScreenConfig$default64, createScreenConfig$default65, createScreenConfig$default66, createScreenConfig$default67, createScreenConfig$default68, createScreenConfig$default69, createScreenConfig$default70, createScreenConfig$default71, createScreenConfig$default72, createScreenConfig$default73, createScreenConfig$default74, createScreenConfig$default75, createScreenConfig$default76, createScreenConfig$default77, createScreenConfig$default78, createScreenConfig$default79, createScreenConfig$default80, SimpleScreenConfigKt.createScreenConfig$default(passengersScreenDestination, TopBarConfiguration.copy$default(defaultTopBarConfig4, false, valueOf4, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3363getLambda83$app_kombardoProd(), 2, null), SimpleScreenConfigKt.createScreenConfig$default(PassengerCountScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, valueOf4, back, null, 9, null), null, composableSingletons$ScreenConfigurationsKt.m3364getLambda84$app_kombardoProd(), 2, null), SimpleScreenConfigKt.createScreenConfig$default(PassengerHelpScreenDestination.INSTANCE, null, null, null, 7, null), SimpleScreenConfigKt.createScreenConfig$default(CheckoutPassengerCreateScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3365getLambda85$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(CheckoutPassengerEditScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3366getLambda86$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(CheckoutDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3367getLambda87$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(VehicleSelectorScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3368getLambda88$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(PaymentScreenDestination.INSTANCE, TopBarConfiguration.copy$default(companion.getDefaultTopBarConfig(), false, Integer.valueOf(R.string.payment_title), back, CollectionsKt.emptyList(), 1, null), null, composableSingletons$ScreenConfigurationsKt.m3369getLambda89$app_kombardoProd(), 2, null), SimpleScreenConfigKt.createScreenConfig$default(ReceiptScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3371getLambda90$app_kombardoProd(), 2, null), SimpleScreenConfigKt.createScreenConfig$default(AddExistingTicketScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3372getLambda91$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(BarcodeDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3373getLambda92$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(FoodBarcodeDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3374getLambda93$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(LoungeBarcodeDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3375getLambda94$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(SaleOnBoardBarcodeDetailsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3376getLambda95$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(RefundReceiptScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, composableSingletons$ScreenConfigurationsKt.m3377getLambda96$app_kombardoProd(), 2, null), SimpleScreenConfigKt.createScreenConfig$default(DeveloperNavigationScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, null, 6, null), SimpleScreenConfigKt.createScreenConfig$default(DeveloperInputComponentsScreenDestination.INSTANCE, null, null, composableSingletons$ScreenConfigurationsKt.m3378getLambda97$app_kombardoProd(), 3, null), SimpleScreenConfigKt.createScreenConfig$default(DeveloperComponentsScreenDestination.INSTANCE, new TopBarConfiguration(false, null, null, null, 14, null), null, null, 6, null), SimpleScreenConfigKt.createScreenConfig$default(DeveloperBottomSheetWithStickyScreenDestination.INSTANCE, null, null, null, 7, null)});
    }

    public static final List<SimpleScreenConfig> getScreenConfigurations() {
        return screenConfigurations;
    }
}
